// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2020-2022 grommunio GmbH

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_URL = 'AUTH_URL';

export const DELETE_TASKS_DATA = 'DELETE_TASKS_DATA';
export const DELETE_TASK_LIST_DATA = "DELETE_TASK_LIST_DATA";
export const DELETE_CONTACTS_DATA = 'DELETE_CONTACTS_DATA';
export const DELETE_NOTES_DATA = 'DELETE_NOTES_DATA';

export const FETCH_CONTACTS_DATA = 'FETCH_CONTACTS_DATA';

export const FETCH_EVENTS_DATA = 'FETCH_EVENTS_DATA';
export const FETCH_MAILS_DATA = 'FETCH_MAILS_DATA';
export const FETCH_MAIL_FOLDERS_DATA = 'FETCH_MAIL_FOLDERS_DATA';
export const FETCH_TASKS_DATA = 'FETCH_TASKS_DATA';
export const FETCH_TASK_LISTS_DATA= 'FETCH_TASK_LISTS_DATA';
export const FETCH_USER_CALENDER_DATA= 'FETCH_USER_CALENDER_DATA';

export const FETCH_PEOPLE_DATA = 'FETCH_PEOPLE_DATA';

export const PATCH_TASK_DATA = 'FETCH_PEOPLE_DATA';
export const POST_TASK_DATA = 'POST_TASK_DATA';
export const POST_TASK_LIST_DATA = 'POST_TASK_LIST_DATA';
export const POST_NOTE_DATA = 'POST_NOTE_DATA';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const FETCH_NOTES_DATA = 'FETCH_NOTES_DATA';

export const POST_EVENT_DATA = 'POST_EVENT_DATA';
export const PATCH_EVENT_DATA = "PATCH_EVENT_DATA";

export const SET_ME = "SET_ME";
export const SET_GAB_CONTACTS_SELECTION = "SET_GAB_CONTACTS_SELECTION";
export const SET_GAB_OPEN = "SET_GAB_OPEN";

export const DELETE_MESSAGE_DATA = "DELETE_MESSAGE_DATA";

export const PATCH_MESSAGE_DATA = "PATCH_MESSAGE_DATA";

export const FETCH_MESSAGE_CATEGORIES = "FETCH_MESSAGE_CATEGORIES";